#
# Copyright (c) 2017 Jens von Pilgrim.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#   Jens von Pilgrim - Initial API and implementation
#
sudo: required
language: node_js
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y oracle-java8-set-default
node_js:
  - "6"
